### ISSUE TITLE
Analysis scripts

### ISSUE THREAD

**Issue by ChelseaCHENX** [theislab/2018_Angelidis#1]
Hi there!

First thanks so much for sharing this atlas and scripts - really cool research! Just wonder if you guys may also want to share scripts regarding data analyses - there are a lot of detailed refined steps, eg, ambient RNA identification, and it might be less straightforward to understand from textual description only. 

Maybe one less relevant question but I also wonder why in this paper Scanpy was not used in most analyses - just curious to know if there should be certain technical or other considerations - eg, in large-scale integrated scRNA-seq analysis.

Thanks a lot!!

**Comment by lkmklsmn** [comment]
Hi Chelsea and thanks for your kind words. Some of the (pre-)processing steps are indeed missing from the repo but are described in the manuscript. With regards to Scanpy, the reason why it was not used is because of personal preference to code in R vs Python at that time. There were no technical considerations. Indeed Scanpy is a great tool for large-scale scRNAseq analysis and highly recommended!
